apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.cassandra.app }}"
  name: "{{ .Values.cassandra.name }}"
spec:
  ports:
    - port: 9042
  selector:
    app: "{{ .Values.cassandra.app }}"