apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.cortex.app }}"
  name: "{{ .Values.cortex.name }}"
spec:
  type: "{{ .Values.cortex.type }}"
  ports:
    - port: {{ .Values.cortex.service.port}}
  selector:
    app: "{{ .Values.cortex.app }}"