apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.cortex.app }}"
  name: "{{ .Values.cortex.name }}"
spec:
  ports:
    - port: 9001
  selector:
    app: "{{ .Values.cortex.app }}"