apiVersion: v1
kind: Service
metadata:
  labels:
    app:  "{{ .Values.elasticsearch.app }}"
  name:  "{{ .Values.elasticsearch.name }}"
spec:
  ports:
    - port: 9200
  selector:
    app: "{{ .Values.elasticsearch.app }}"