apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Values.elasticsearch.name }}"
  labels:
    app: "{{ .Values.elasticsearch.app }}"
spec:
  serviceName: elasticsearch
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.elasticsearch.app }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.elasticsearch.app }}"
    spec:
      terminationGracePeriodSeconds: 1800
      initContainers:
        - name: init
          image: debian:stable-slim
          command:
            - bash
            - "-c"
            - "mkdir -p /usr/share/elasticsearch/data && chmod -R 777 /usr/share/elasticsearch/data"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: "{{ .Values.elasticsearch.name }}"
          image: "{{ .Values.elasticsearch.image }}:{{ .Values.elasticsearch.tag }}"
          ports:
            - containerPort: 9200
              name: http
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "500m"
              memory: 512Mi
          env:
            - name: "node.name"
              value: es
            - name: "cluster.name"
              value: es-docker-cluster
            - name: "discovery.type"
              value: single-node
            - name: "bootstrap.memory_lock"
              value: "true"
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.ES_JAVA_OPTS }}
            - name: "xpack.security.enabled"
              value: "false"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          emptyDir: {}