apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thehive-application-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /cortex
            pathType: Prefix
            backend:
              service:
                name: cortex
                port:
                  number: 9001
          - path: /minio
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9090
          - path: /thehive
            pathType: Prefix
            backend:
              service:
                name: thehive
                port:
                  number: 9000       