apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.minio.app }}"
  name: "{{ .Values.minio.name }}"
spec:
  type: "{{ .Values.minio.type }}"
  ports:
    - name: console
      port: 9090
    - name: s3-api
      port: 9000  
      
  selector:
    app: "{{ .Values.minio.app }}"