apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.thehive.app }}"
  name: "{{ .Values.thehive.name }}"
spec:
  type: "{{ .Values.thehive.type }}"
  ports:
    - port: {{ .Values.thehive.service.port }}
  selector:
    app: "{{ .Values.thehive.app }}"