apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.thehive.name }}"
  labels:
    app: "{{ .Values.thehive.app }}"
spec:
  replicas: {{ .Values.thehive.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Values.thehive.app }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.thehive.app }}"
    spec:
      serviceAccountName: thehive
      containers:
        - name: "{{ .Values.thehive.name }}"
          image: "{{ .Values.thehive.image }}:{{ .Values.thehive.tag }}"
          command:
            - "/opt/thehive/entrypoint"
            - "--secret"
            - "SuperSecretForKubernetes"
            - "--cql-hostnames"
            - "cassandra"
            - "--no-cql-wait"
            - "--no-config-cortex"
            - "--kubernetes"
            - "--index-backend"
            - "elasticsearch"
            - "--es-hostnames"
            - "elasticsearch"
            - "--s3-endpoint"
            - "http://minio:9000"
            - "--s3-access-key"
            - "minioadmin"
            - "--s3-secret-key"
            - "minioadmin"
            - "--s3-use-path-access-style"
            - "--cluster-min-nodes-count"
            - "0"
          ports:
            - containerPort: 9000
              name: http
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 512Mi

#          startupProbe:
#            httpGet:
#              path: /api/v1/status/public
#              port: 9000
#            failureThreshold: 30
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /api/v1/status/public
#              port: 9000
#            periodSeconds: 10